services:
  - type: web
    name: fashion-churn-12field
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fashionChurn.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
